packages:
  - "app"
  - "tools"
  - "tests"
  - "options"
  - "package/snap"
  - "server/prisma"
  - "package/node"
  - "package/github"
  - "package/vscode"
  - "package/cli"
  - "docs"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
