packages:
  - 'server'
  - 'app'
  - 'cli'
  - 'services'
  - 'routers'
  - 'tools'
  - 'tests'
  - 'options'
  - 'package'
  - 'snap'
  - 'prisma'

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
